<html>
  <head>
    <title>Island-V FiveM Server</title>
  </head>
  <body>
    <header>
        <img src="https://cdn.discordapp.com/attachments/1086594515856523294/1086619444710740008/3F3D7C79-F6EA-4A8E-B18B-5054D65A44F0.jpg" alt="IslandV" width="500" height="270">
        <h1>Wilkommen bei Island-V schön das du vorbei guckst</h1>
      <nav>
        <ul>
         
        </ul>
      </nav>
    </header>
    <main>
      <section id="about">
        <h2>About Island-V</h2>
        <p>IslandV ist ein guter Fivem Server mit netten teamler netten Spielern und gutem rp. Unsere Teamler helfen immer egal wobei.</p>
      </section>
      <section id="rules">
        <h2><section id="rules">
            <h2>Regelwerk ist im <a href="https://discord.gg/Guvr3ufd">Discord</a>:</h2>
            <ol></li>
            </ol>
          </section>
           </h2>
        <ol></li>
        </ol>
      </section>
      <section id="features">
        <h2>Features</h2>
        <ul>
          <li>Custom outifits</li>
          <li>Realistisches RP</li>
          <li>Job system ohne fehler</li>
          <li>Auto tuning mit vielen optionen</li>
          <li>Gutes Bank system</li>
          <h2>Team bewerbung tutorial</h2>
        <ul>
          <li>Als erstes geht ihr auf usnerem discord: https://discord.gg/Guvr3ufd</li>
          <li>Dann verifiziert ihr euch</li>
          <li>Nun geht ihr zum Channel Team bewerbung und füllt die vorlage aus in dem ihr ein ticket öffnet </li>
          
          <h2>Fivem download tutorial</h2>
          <ul>
            <li>Als erstes geht ihr auf die seite von fivem dann installiert ihr euch und meldet euch an.</li>
            <li>Dann geht ihr auf die server list und gibt Island-V ein joint fertig du bist drinne.</li>
            <img src="" alt="Beschreibung des Bildes">
        </ul>
      </section>
        </form>
      </section>
    </main>
    <footer>
      <p>&copy; 2023 Island-V FiveM Server</p>
      <style>
        body {
          background-color: lightblue;
        }
       <section id="video">
  <h2>Unser discord tut</h2>
  <iframe width="560" height="315" src="https://youtu.be/MxsjjsdvV3U" frameborder="0" allowfullscreen></iframe>
</section>
        <img src="https://cdn.discordapp.com/attachments/1085624545148420126/1087787420432478268/islandvbild.png" alt="IslandV" width="500" height="270">

      </style>
      
    </footer>
  </body>
</html>
